# Generated by Django 4.2.2 on 2023-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_task_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='starting_time',
        ),
        migrations.AddField(
            model_name='task',
            name='ending_time',
            field=models.TimeField(max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
