# Generated by Django 4.2.2 on 2023-06-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_task_ending_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ending_time',
            field=models.CharField(default=models.TimeField(max_length=10), max_length=10),
        ),
    ]
