# Generated by Django 4.2.2 on 2023-06-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_task_ending_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='starting_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ending_time',
        ),
    ]
