# Generated by Django 4.2.2 on 2023-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_rename_starting_time_task_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='ending_time',
            field=models.TimeField(default='00:00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='starting_time',
            field=models.TimeField(default='00:00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='day',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
