# Generated by Django 4.2.2 on 2023-06-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_remove_task_time_task_ending_time_task_starting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bool_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
