# Generated by Django 4.2.2 on 2023-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_alter_task_bool_check_alter_todolist_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
