# Generated by Django 4.2.2 on 2023-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_task_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(default='skip-skip', max_length=200),
        ),
    ]
