# Generated by Django 4.2.2 on 2023-06-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='starting_time',
        ),
    ]
